// $(document).ready(function() {
$("#card1").flip()
$("#card2").flip()
$("#card3").flip()
$("#card4").flip()
$("#card5").flip()
$("#card6").flip()
$("#card7").flip()
$("#card8").flip()
$("#card9").flip()

$("#card-1").flip()
$("#card-2").flip()
$("#card-3").flip()
$("#card-4").flip()
$("#card-5").flip()
$("#card-6").flip()
$("#card-7").flip()
$("#card-8").flip()
$("#card-9").flip()
